// routes ok
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import SubscriptionLanding from "@/pages/SubscriptionLanding";
import SubscribePage from "@/pages/SubscribePage";
import BundlePage from "@/pages/BundlePage";
import LandingPage from "@/pages/LandingPage";
import Dashboard from "@/pages/Dashboard";
import Chapters from "@/pages/Chapters";
import ChapterDetail from "@/pages/ChapterDetail";
import Actions from "@/pages/Actions";
import Teachers from "@/pages/Teachers";
import Community from "@/pages/Community";
import Auth from "@/pages/Auth";
import NotFound from "@/pages/NotFound";
import FounderDashboard from "@/pages/FounderDashboard";
import VentureBuilder from "@/pages/VentureBuilder";
import Marketplace from "@/pages/Marketplace";
import MarketplaceDetail from "@/pages/MarketplaceDetail";
import StudentReview from "@/pages/StudentReview";
import StudentWallet from "@/components/StudentWallet";
import MentorReview from "@/components/MentorReview";
import StudentWorkspace from "@/pages/StudentWorkspace";
import Programs from "@/pages/Programs";
import StudentWorkbook from "@/pages/StudentWorkbook";
import ProgramDetail from "@/pages/ProgramDetail";
import GameLanding from "@/pages/GameLanding";
import GameSession from "@/pages/GameSession";
import ClubLogin from "@/pages/ClubLogin";
import ClubTeacher from "@/pages/ClubTeacher";
import ClubStudent from "@/pages/ClubStudent";
import BookDashboard from "@/pages/BookDashboard";
import BookChapter from "@/pages/BookChapter";
import BookLogin from "@/pages/BookLogin";
import PrivacyPolicy from "@/pages/PrivacyPolicy";
